### ISSUE TITLE
[Bug]: Error: Text strings must be rendered within a <Text> component.

### ISSUE THREAD

**Issue by athmap** [SahilAggarwal2004/react-text-to-speech#5]
### Provide environment information

 "react-text-to-speech": "^0.14.6",

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code help us address them faster

npm install react-text-to-speech --save

### To reproduce

After implementing this in typescript code getting below issue
I was trying to run the basic code which is mentioned in github 

Code:
```ts
import React from "react";
import { useSpeech } from "react-text-to-speech";

export default function App() {
  const {
    Text, // Component that returns the modified text property
    speechStatus, // String that stores current speech status
    isInQueue, // Boolean that stores whether a speech utterance is either being spoken or present in queue
    start, // Function to start the speech or put it in queue
    pause, // Function to pause the speech
    stop, // Function to stop the speech or remove it from queue
  } = useSpeech({ text: "This library is awesome!" });

  return (
    <div style={{ display: "flex", flexDirection: "column", rowGap: "1rem" }}>
      <Text />
      <div style={{ display: "flex", columnGap: "0.5rem" }}>
        {speechStatus !== "started" ? <button onClick={start}>Start</button> : <button onClick={pause}>Pause</button>}
        <button onClick={stop}>Stop</button>
      </div>
    </div>
  );
}
```

Error
Error: Text strings must be rendered within a <Text> component.

This error is located at:

### Describe the bug

Error
Error: Text strings must be rendered within a <Text> component.

This error is located at:

### Expected behavior

It should work as you mentioned in the doc.

**Comment by SahilAggarwal2004** [comment]
Hmm looks weird... It's working absolutely fine on my end.
Are you using plain React.js or any framework like Next.js or Remix.js?
Also, can you provide any other important information that I should be knowing regarding this issue?

**Comment by athmap** [comment]
I am using react native. Please check the below version
  "react": "18.2.0",
  "react-dom": "18.2.0",
  "react-native": "0.72.4",

**Comment by SahilAggarwal2004** [comment]
Ohh, now I got it.
Actually, `react-text-to-speech` uses the WebSpeech API available in modern browsers as its backbone. Since this API is not available on Android and iOS, I never targetted and tested this library for `react-native`. And this is probably the reason behind your issue.
Fortunately, there are some other libraries that provide text-to-speech functionality in `react-native` like [react-native-tts](https://www.npmjs.com/package/react-native-tts) or [react-native-voice](https://www.npmjs.com/package/@react-native-voice/voice). Although it seems like both of them are no longer maintained, but I guess you should give them a try.
